### ISSUE TITLE
TODO's / Proposal

### ISSUE THREAD

**Issue by Nold360** [Nold360/ffmd-ansible#1]
# ToDo:

## Roles

We need a role for every component of the infrastructure:
- [ ] **backup**: I will most likely use `borgbackup` for this. But i havn't found a nice role, yet. might build my own.
- [x] **common**: Packages & stuff for all servers
- [x] **sudo**: .. configures sudo
- [ ] **gateway**: FF-Gateway docker configuration & routing
  - [ ] Including: docker-containers, routing & other services
- [x] **docker**: installs docker
- [ ] **ssh**: confiigures sshd
- [ ]  **users**: adds admin users & their ssh-keys from https://github.com/FreifunkMD/ffmd-ssh-keys
- [ ] **monitor[ing]** - I would use icinga2 for this. 
  - [ ] client configuration
  - [ ] server configuration
- [ ] **...?** 

## Automation

- How/where do we execute ansible playbooks? To prevent the application of non-upstream changes, this should be automatically done. How do you do that with ansible? 

  - My first guess would be to use a CI and incl. a branching concept, so feature-branches get applied to dev/test-nodes and not production. I'm used to Gitlab-CI, but to keep independence from the version control system we should use something else. I heart a lot of bad things about jenkins, still everybody seems to be using it... 

- I've will migrate https://github.com/penguineer/ansible into this.

What else do we need to configure/manage?

**Comment by Nold360** [comment]
Will be discussed in https://github.com/FreifunkMD/ansible/issues/3

**Comment by cutec-chris** [comment]
Hoi, 
https://github.com/FreifunkMD/ansible ist archiviert, wurde das ganze in irgendwas anders überführt oder ist https://redmine.n39.eu/issues/494 nicht mehr aktuell ?
